lightning:
  callbacks:
    video_logger:
      target: unimumo.loggers.MotionVQVAELogger
      params:
        motion_dir: data/motion
        epoch_frequency: 10
        batch_frequency: 4000
        max_video_per_generation: 4
        max_video_logged: 120
        motion_fps: 60
        disabled: false
  trainer:
    benchmark: true
    devices: 2
    num_nodes: 1
    accelerator: gpu
    max_epochs: -1
